/*

 BACKGROUND-MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 39 x 34
   Tile set      : D:\workspace\off-orbit-gb\raw\background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundMapWidth 39
#define BackgroundMapHeight 34
#define BackgroundMapBank 0

extern const unsigned char BackgroundMap[];

/* End of BACKGROUND-MAP.H */
