/*

 TITLE-MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\workspace\off-orbit-gb\raw\title.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 43
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TitleMapWidth 20
#define TitleMapHeight 18
#define TitleMapBank 0

extern const unsigned char TitleMap[];

/* End of TITLE-MAP.H */
